### PR TITLE
Upgrade all third-party libraries to latest version

### PR DESCRIPTION
**Pull request by Zavster**

### CODE REVIEW

**Comment by Zavster** [comment]
**Build STARTED**
https://jenkins.d3xsystems.com/job/d3x-morpheus-pipeline/job/PR-138/1/

**Comment by Zavster** [comment]
**Build SUCCESS**
https://jenkins.d3xsystems.com/job/d3x-morpheus-pipeline/job/PR-138/1/

**Review by tipplerow — DISMISSED** [review]
Looks good

**Comment by Zavster** [comment]
**Build STARTED**
https://jenkins.d3xsystems.com/job/d3x-morpheus-pipeline/job/PR-138/2/

**Comment by Zavster** [comment]
**Build SUCCESS**
https://jenkins.d3xsystems.com/job/d3x-morpheus-pipeline/job/PR-138/2/

**Comment by Zavster** [comment]
**Build STARTED**
https://jenkins.d3xsystems.com/job/d3x-morpheus-pipeline/job/PR-138/3/

**Comment by Zavster** [comment]
**Build SUCCESS**
https://jenkins.d3xsystems.com/job/d3x-morpheus-pipeline/job/PR-138/3/

**Comment by Zavster** [comment]
**Build STARTED**
https://jenkins.d3xsystems.com/job/d3x-morpheus-pipeline/job/PR-138/4/

**Comment by Zavster** [comment]
**Build SUCCESS**
https://jenkins.d3xsystems.com/job/d3x-morpheus-pipeline/job/PR-138/4/

**Review by tipplerow — APPROVED** [review]
Looks good

**Pull request merged**
