### PR TITLE
Upgrade snakeyaml due to CVE

### PR DESCRIPTION
**Pull request by Zavster**

### CODE REVIEW

**Comment by Zavster** [comment]
**Build STARTED**
https://jenkins.d3xsystems.com/job/d3x-morpheus-pipeline/job/PR-143/1/

**Comment by Zavster** [comment]
**Build FAILURE**
https://jenkins.d3xsystems.com/job/d3x-morpheus-pipeline/job/PR-143/1/

**Comment by Zavster** [comment]
**Build STARTED**
https://jenkins.d3xsystems.com/job/d3x-morpheus-pipeline/job/PR-143/2/

**Comment by Zavster** [comment]
**Build FAILURE**
https://jenkins.d3xsystems.com/job/d3x-morpheus-pipeline/job/PR-143/2/

**Comment by Zavster** [comment]
**Build STARTED**
https://jenkins.d3xsystems.com/job/d3x-morpheus-pipeline/job/PR-143/3/

**Comment by Zavster** [comment]
**Build SUCCESS**
https://jenkins.d3xsystems.com/job/d3x-morpheus-pipeline/job/PR-143/3/

**Review by tipplerow — APPROVED** [review]
Looks good

**Pull request merged**
